name: Auto Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[build skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          java-package: jdk
          architecture: x64
      - run: mvn -B package --file pom.xml --errors
      - run: mkdir staging && cp target/MobCapturer-*.jar staging
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v2
        with:
          name: MobCapturer.jar
          path: staging